version: '3.4'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
  site-backend:
    build:
      dockerfile: .docker/site-backend.Dockerfile
      context: .
    entrypoint: /app/entrypoint.sh
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - RSS_FEED=https://feeds.soundcloud.com/users/soundcloud:users:610582557/sounds.rss
      - VIRTUAL_HOST=api.znprod.io
      - LETSENCRYPT_HOST=api.znprod.io
      - LETSENCRYPT_EMAIL=znprod@yandex.ru
  site-frontend:
    build:
      dockerfile: .docker/site-frontend.Dockerfile
      context: .
    ports:
    - 8080:80
    environment:
      - VIRTUAL_HOST=znprod.io
      - LETSENCRYPT_HOST=znprod.io
      - LETSENCRYPT_EMAIL=znprod@yandex.ru
volumes:
  certs:
  vhost.d:
  html: